# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoSport' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoSport
  pod 'YandexMapsMobile', ’4.0.0-full’
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'GoogleSignIn'
  pod 'FSCalendar'
  pod 'GoogleSignIn'
end
